// <auto-generated />
namespace SampleApp.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Addeduserroles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addeduserroles));
        
        string IMigrationMetadata.Id
        {
            get { return "201710021357439_Added user roles"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
