//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Computers.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GPU
    {
        public int Id { get; set; }
        public string Vendor { get; set; }
        public string Model { get; set; }
        public int Memory { get; set; }
        public int GPUTypeId { get; set; }
        public int ComputerId { get; set; }
    
        public virtual Computer Computer { get; set; }
        public virtual GPUType GPUType { get; set; }
    }
}
